modLoader = "javafml"
loaderVersion = "[47,)"
license = "${mod_license}"
issueTrackerURL = ""

[[mods]]
    modId = "${mod_id}"
    version = "${mod_version}"
    displayName = "${mod_name}"
    authors = "ponchisao"
    description = '''
Diagnoses and corrects autocrafting liveness problems in large Applied Energistics 2 networks.
'''

[[dependencies.${mod_id}]]
    modId = "forge"
    mandatory = true
    versionRange = "[47,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1,1.21)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "ae2"
    mandatory = true
    versionRange = "[15.4.1,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "expatternprovider"
    mandatory = false
    versionRange = "*"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "mae2"
    mandatory = false
    versionRange = "*"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "ae2ct"
    mandatory = false
    versionRange = "*"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "ae2netanalyser"
    mandatory = false
    versionRange = "*"
    ordering = "AFTER"
    side = "BOTH"
